name: Frontend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  NODE_VERSION: '18.x'

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v3

    - name: Setting up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Caching NodeJS Modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Installing package dependencies
      run: |
        cd frontend
        npm ci

    - name: Linting Job
      run: |
        cd frontend
        npm run lint

  testing-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v3

    - name: Setting up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Caching NodeJS Modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
            
    - name: Installing package dependencies
      run: |
        cd frontend
        npm ci

    - name: Testing backend
      run: |
        cd frontend
        npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [linting-job, testing-job]

    steps:
    - name: Checking out
      uses: actions/checkout@v3

    - name: Setting up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Caching NodeJS Modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Running package install, build up and test
      run: |
        cd frontend
        npm ci
        npm run build --if-present
        npm test

    - name: Docker build repository
      env:
        IMAGE_TAG: latest
        REPOSITORY: movie-picture-fe
        REACT_APP_MOVIE_API_URL: ${{ secrets.REACT_APP_MOVIE_API_URL }}
      run: |
        cd frontend
        REACT_APP_MOVIE_API_URL="http://$REACT_APP_MOVIE_API_URL"
        docker build --build-arg=REACT_APP_MOVIE_API_URL -t $REPOSITORY:$IMAGE_TAG .

    - name: Configuring secrets to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Access to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker tagging image
      env:
        IMAGE_TAG: latest
        REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        REPOSITORY: movie-picture-fe
      run: docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Docker pushing image to ECR AWS
      env:
        IMAGE_TAG: latest
        REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        REPOSITORY: movie-picture-fe
      run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Login to EKS Cluster
      env:
        CLUSTER_NAME: my-cluster
        REGION: ${{ secrets.AWS_REGION }}
      run: aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

    - name: Kustomizing Image
      env:
        IMAGE_TAG: latest
        REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        REPOSITORY: movie-picture-fe
      run: |
        cd frontend/k8s
        kustomize edit set image $REPOSITORY=$REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Kustomizing application build
      run: |
        cd frontend/k8s
        kustomize build | kubectl apply -f -
